name: Audit

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - dev
    paths:
      - "**/Cargo.lock"
      - "**/Cargo.toml"
  pull_request:
    branches:
      - dev
    paths:
      - "**/Cargo.lock"
      - "**/Cargo.toml"

jobs:
  audit-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  audit-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6
          run_install: true

      - name: audit
        run: pnpm audit