name: Test

on:
  push:
    branches:
      - dev
    paths:
      - '.github/workflows/test.yml'
      - 'src/**'
  pull_request:
    branches:
      - dev
    paths:
      - '.github/workflows/test.yml'
      - 'src/**'

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Install clippy with stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      
      - uses: Swatinem/rust-cache@v1
      
      - name: Install gtk on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0
          
      - name: Run tests 
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path=Cargo.toml --release